spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${ORDER_SERVICE_DATABASE_NAME:flashbite_order}
    username: ${DATABASE_USERNAME:flashbite}
    password: ${DATABASE_PASSWORD:flashbite}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public
    table: flyway_schema_history
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
